

"use client";

import { useState, useRef, useEffect } from "react";
import { supabase } from "@/lib/supabase-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, Send, MessageSquare, BrainCircuit, User, Sparkles } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";

interface Message {
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

interface LabReportChatProps {
  reportId: string;
  fileName: string;
}

// Helper to render bold text generated by Gemini (e.g., **bold text**)
const formatMessage = (text: string) => {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={index} className="font-semibold text-indigo-900">
          {part.slice(2, -2)}
        </strong>
      );
    }
    // Remove stray markdown artifacts but keep the structure
    return <span key={index}>{part.replace(/#{1,6}\s+/g, "").replace(/`/g, "")}</span>;
  });
};

export function LabReportChat({ reportId, fileName }: LabReportChatProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const scrollAreaRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollAreaRef.current) {
      scrollAreaRef.current.scrollTop = scrollAreaRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || loading) return;

    const userMessage: Message = {
      role: "user",
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setLoading(true);
    setError(null);

    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) {
        throw new Error("Please sign in to chat");
      }

      const {
        data: { session },
      } = await supabase.auth.getSession();

      const headers: HeadersInit = {
        "Content-Type": "application/json",
      };
      if (session?.access_token) {
        headers.Authorization = `Bearer ${session.access_token}`;
      }

      const response = await fetch("/api/lab/chat", {
        method: "POST",
        headers,
        body: JSON.stringify({
          reportId,
          question: userMessage.content,
          userId: user.id,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to get answer");
      }

      const assistantMessage: Message = {
        role: "assistant",
        content: data.answer,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, assistantMessage]);
    } catch (err: any) {
      setError(err.message || "Failed to send message");
      setMessages((prev) => prev.slice(0, -1));
    } finally {
      setLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <Card className="h-full flex flex-col border-blue-100 shadow-md bg-white/50 backdrop-blur-sm">
      <CardHeader className="border-b border-gray-100 pb-4 bg-white rounded-t-xl">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center shrink-0 border border-blue-200">
            <BrainCircuit className="h-5 w-5 text-blue-700" />
          </div>
          <div>
            <CardTitle className="text-lg text-gray-900">AI Report Assistant</CardTitle>
            <p className="text-sm text-gray-500 font-medium truncate max-w-[250px] md:max-w-md">
              Discussing: <span className="text-blue-600">{fileName}</span>
            </p>
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex flex-col flex-1 min-h-0 p-4 bg-gray-50/30">
        <ScrollArea
          ref={scrollAreaRef}
          className="flex-1 pr-4 mb-4"
          style={{ maxHeight: "400px" }}
        >
          {messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center py-12 px-4 space-y-3">
              <div className="h-16 w-16 rounded-full bg-blue-50 flex items-center justify-center mb-2 shadow-inner">
                <Sparkles className="h-8 w-8 text-blue-400" />
              </div>
              <h3 className="font-semibold text-gray-700">How can I help you?</h3>
              <p className="text-sm text-gray-500 max-w-xs">
                Ask me to explain specific values, flag abnormal results, or summarize your overall health metrics.
              </p>
              <div className="mt-4 p-3 bg-white rounded-lg border border-gray-200 text-xs text-left shadow-sm w-full max-w-xs">
                <span className="font-semibold text-blue-600">Try asking:</span><br/>
                <span className="text-gray-600">"What do my cholesterol levels mean?"</span>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {messages.map((message, index) => (
                <div
                  key={index}
                  className={`flex items-start gap-3 ${
                    message.role === "user" ? "flex-row-reverse" : "flex-row"
                  }`}
                >
                  {/* Avatar */}
                  <div className={`h-8 w-8 rounded-full flex items-center justify-center shrink-0 mt-1 shadow-sm ${
                    message.role === "user" ? "bg-blue-600" : "bg-white border border-gray-200"
                  }`}>
                    {message.role === "user" ? (
                      <User className="h-4 w-4 text-white" />
                    ) : (
                      <BrainCircuit className="h-4 w-4 text-blue-600" />
                    )}
                  </div>

                  {/* Message Bubble */}
                  <div
                    className={`max-w-[85%] rounded-2xl p-4 shadow-sm ${
                      message.role === "user"
                        ? "bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-tr-sm"
                        : "bg-white border border-gray-100 text-gray-800 rounded-tl-sm"
                    }`}
                  >
                    <div className="text-sm whitespace-pre-wrap leading-relaxed">
                      {message.role === "user" ? message.content : formatMessage(message.content)}
                    </div>
                    <p
                      className={`text-[10px] mt-2 font-medium ${
                        message.role === "user"
                          ? "text-blue-100 text-right"
                          : "text-gray-400 text-left"
                      }`}
                    >
                      {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                  </div>
                </div>
              ))}
              {loading && (
                <div className="flex items-start gap-3">
                  <div className="h-8 w-8 rounded-full bg-white border border-gray-200 flex items-center justify-center shrink-0 mt-1 shadow-sm">
                    <BrainCircuit className="h-4 w-4 text-blue-600" />
                  </div>
                  <div className="bg-white border border-gray-100 rounded-2xl rounded-tl-sm p-4 shadow-sm">
                    <div className="flex items-center gap-2 text-blue-600">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span className="text-sm font-medium">Analyzing report...</span>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}
        </ScrollArea>

        {error && (
          <div className="mb-3 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600 font-medium flex items-center gap-2">
            <span className="h-1.5 w-1.5 rounded-full bg-red-600" />
            {error}
          </div>
        )}

        {/* Input Area */}
        <div className="flex gap-2 bg-white p-2 rounded-xl border border-gray-200 shadow-sm focus-within:ring-2 focus-within:ring-blue-500/20 focus-within:border-blue-400 transition-all">
          <Input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Ask about your lab results..."
            disabled={loading}
            className="flex-1 border-0 focus-visible:ring-0 shadow-none bg-transparent"
          />
          <Button 
            onClick={handleSend} 
            disabled={loading || !input.trim()}
            className="rounded-lg bg-blue-600 hover:bg-blue-700 shadow-sm transition-colors"
          >
            {loading ? (
              <Loader2 className="h-4 w-4 animate-spin text-white" />
            ) : (
              <Send className="h-4 w-4 text-white" />
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}